title: ãã‚‹ã¿ã®ã‚­ãƒ£ãƒ©ãƒ¡ãƒªã‚¼
description: >
  ğŸ­ã“ã®è¡—ã§ä¸€ç•ªç”˜ã„ã®ã¯ã€ã‚ãŸã—ã®è¡€ã ã‚ˆï¼ğŸ°
index: manual

author: 8amjp
image: site-icon.png
type: novel
card: summary
google_analytics: UA-41627578-3
twitter:
  username: 8amjp

# Build settings
markdown: kramdown
theme: minima

plugins:
  - jekyll-seo-tag