title: ãã‚‹ã¿ã®ã‚­ãƒ£ãƒ©ãƒ¡ãƒªã‚¼
author: 8amjp
description: >
  ğŸ­ã“ã®è¡—ã§ä¸€ç•ªç”˜ã„ã®ã¯ã€ã‚ãŸã—ã®è¡€ã ã‚ˆï¼ğŸ°
  [ãŠè“å­ç³»SF/é€£ä½œçŸ­ç·¨]
index: manual

type: novel
google_analytics: UA-41627578-3
twitter:
  username: 8amjp

# Build settings
markdown: kramdown
theme: minima

plugins:
  - jekyll-seo-tag
gems:
  - jekyll-octicons