title: ãã‚‹ã¿ã®ã‚­ãƒ£ãƒ©ãƒ¡ãƒªã‚¼
author: è¶³ç¾½å·æ°¸éƒ½
description: >
  ğŸ­ã“ã®è¡—ã§ä¸€ç•ªç”˜ã„ã®ã¯ã€ã‚ãŸã—ã®è¡€ã ã‚ˆï¼ğŸ°
image: https://8amjp.github.io/site-icon.png
type: novel
card: summary
index: manual
twitter_username: 8amjp
github_username:  8amjp
google_analytics: UA-41627578-3

# Build settings
markdown: kramdown
theme: minima